function qrySkillEnable(sk)
	local ske = skillsEnable[sk]
	-- ain debug
	if not ske then
		return false
	end
	local skl = {}
	if type(ske) == "function" then
		if ske() then
			skl = string.split(ske(), ",")
		else
			return false
		end
	else
		skl = string.split(ske, ",")
	end
	local skr = {}
	for _, p in pairs(skl) do
		skr[p] = true
	end
	if countTab(skr) > 0 then
		return skr
	else
		return false
	end
end

skillEnable = {
	["anying-fuxiang"] = "dodge",
	["anran-zhang"] = "strike",
	["bahuang-gong"] = "force",
	["baihua-cuoquan"] = "cuff",
	["banruo-zhang"] = "strike",
	["beiming-shengong"] = "force",
	["bihai-chaosheng"] = "force",
	["canglang-goufa"] = "hook",
	["canhe-zhi"] = "finger",
	["caoshang-fei"] = "dodge",
	["chongling-jian"] = "sword",
	["chousui-zhang"] = "strike",
	["chuanyun-tui"] = "leg",
	["cihang-bian"] = "whip",
	["cibei-dao"] = "blade",
	["cuixin-zhang"] = "strike",
	["cuogu-shou"] = "hand",
	["dafumo-quan"] = "cuff",
	["dagou-bang"] = "stick",
	["damo-jian"] = "sword",
	["qianzhu-wandushou"] = "hand",
	["dashou-yin"] = "hand",
	["ding-dodge"] = "dodge",
	["duanjia-jianfa"] = "sword",
	["duanjia-quan"] = "cuff",
	["dugu-jiujian"] = "sword",
	["dulong-dafa"] = "force",
	["duoming-jinhua"] = "throwing",
	["fanliangyi-dao"] = "blade",
	["fengmo-zhang"] = "staff",
	["fengyun-shou"] = "hand",
	["fuhu-quan"] = "cuff",
	["fumo-jian"] = "sword",
	["fuqin-shi"] = "whip",
	["furong-jinzhen"] = "throwing",
	["guiyuan-tunafa"] = "force",
	["hamabu"] = "dodge",
	["hamagong"] = "force",
	["hanbing-mianzhang"] = "strike",
	["hanbing-shenzhang"] = "strike",
	["hanbing-zhenqi"] = "force",
	["haotian-zhang"] = "strike",
	["hansha-sheying"] = "throwing",
	["hengshan-jian"] = "sword",
	["hengshan-jianfa"] = "sword",
	["henshan-jianfa"] = "sword",
	["huagong-dafa"] = "force",
	["huagu-mianzhang"] = "strike",
	["huanmo-wubu"] = "dodge",
	["huanmo-longtianwu"] = "dodge",
	["huanyin-zhi"] = "finger",
	["huashan-jianfa"] = "sword",
	["huashan-qigong"] = "force",
	["huashan-shenfa"] = "dodge",
	["huifeng-bian"] = "whip",
	["huifeng-jian"] = "sword",
	["hujia-daofa"] = "blade",
	["huntian-qigong"] = "force",
	["hunyuan-zhang"] = "strike",
	["huoyan-dao"] = "strike",
	["huyan-qiang"] = "spear",
	["jieshou-jiushi"] = "hand",
	["jimie-zhua"] = "claw",
	["jindao-heijian"] = "sword",
	["jingang-quan"] = "cuff",
	["jinshe-jianfa"] = "sword",
	["jinshe-zhangfa"] = "strike",
	["jinshe-zhuifa"] = "throwing",
	["jinwu-daofa"] = "blade",
	["jinyan-gong"] = "dodge",
	["jiuyang-shengong"] = "force",
	["jiuyin-baiguzhua"] = "claw",
	["jiuyin-shenfa"] = "dodge",
	["jiuyin-shenzhang"] = "strike",
	["jiuyin-shenzhua"] = "claw",
	["jiuyin-zhengong"] = "force",
	["juehu-shou"] = "hand",
	["kaishan-fu"] = "axe",
	["kaishan-zhang"] = "strike",
	["kongming-quan"] = "cuff",
	["kuaihuo-zhang"] = "strike",
	["kuihua-feiying"] = "dodge",
	["kuihua-mogong"] = "force",
	["kuihua-shengong"] = "force",
	["kunlun-zhang"] = "strike",
	["kurong-changong"] = "force",
	["lanhua-shou"] = "hand",
	["lengquan-shengong"] = "force",
	["liangyi-jian"] = "sword",
	["lianhua-zhang"] = "strike",
	["lietian-fu"] = "axe",
	["liehuo-jian"] = "sword",
	["lieyan-dao"] = "blade",
	["lingbo-weibu"] = "dodge",
	["lingshe-bianfa"] = "whip",
	["lingshe-quanfa"] = "cuff",
	["lingxu-bu"] = "dodge",
	["linji-zhuang"] = "force",
	["liuhe-daofa"] = "blade",
	["liuyang-zhang"] = "strike",
	["liuye-daofa"] = "blade",
	["longxiang-boruo"] = "force",
	["longzhua-gong"] = "claw",
	["luohan-quan"] = "cuff",
	["luoying-zhang"] = "strike",
	["mantian-huayu"] = "throwing",
	["meinu-quanfa"] = "cuff",
	["miaojia-jianfa"] = "sword",
	["murong-daofa"] = "blade",
	["murong-jianfa"] = "sword",
	["nianhua-zhi"] = "finger",
	["ningxue-shenzhao"] = "claw",
	["ningxue-shenzhua"] = "claw",
	["pangen-fu"] = "axe",
	["pixie-jian"] = "sword",
	["piaomiao-shenfa"] = "dodge",
	["piaoyi-bu"] = "dodge",
	["piaoyi-shenfa"] = "dodge",
	["pinxu-lingfeng"] = "dodge",
	["pomopima-jian"] = "sword",
	["poyu-quan"] = "cuff",
	["qiantian-yiyang"] = "force",
	["qianye-shou"] = "hand",
	["qianzhu-wandushou"] = "hand",
	["qingyan-zhang"] = "strike",
	["qishang-quan"] = "cuff",
	["qixian-wuxingjian"] = "sword",
	["quanzhen-jianfa"] = "sword",
	["ranmu-daofa"] = "blade",
	["riyue-bian"] = "whip",
	["ruyi-dao"] = "blade",
	["ruying-suixingtui"] = "leg",
	["sanhua-zhang"] = "strike",
	["sanyin-zhua"] = "claw",
	["shaolin-shenfa"] = "dodge",
	["shaolin-tantui"] = "leg",
	["shenghuo-lingfa"] = "dagger",
	["shenghuo-shengong"] = "force",
	["shenlong-tuifa"] = "leg",
	["shenxing-baibian"] = "dodge",
	["shenyuan-gong"] = "force",
	["shenzhao-jing"] = "force",
	["shexing-diaoshou"] = "hand",
	["shuishangpiao"] = "dodge",
	["sixiang-zhang"] = "strike",
	["songshan-jian"] = "sword",
	["songshan-qigong"] = "force",
	["songyang-bian"] = "whip",
	["songyang-shou"] = "hand",
	["songyang-zhang"] = "strike",
	["suibo-zhuliu"] = "dodge",
	["suohou-shou"] = "hand",
	["taiji-jian"] = "sword",
	["taiji-quan"] = "cuff",
	["taiji-shengong"] = "force",
	["taishan-jianfa"] = "sword",
	["taixuan-gong"] = "strike",
	["taizu-quan"] = "cuff",
	["tangshi-jianfa"] = "sword",
	["tanzhi-shentong"] = "finger",
	--["tanzhi-shentong"] = "throwing",
	["taxue-wuhen"] = "dodge",
	["tenglong-bifa"] = "dagger",
	["tianmo-dao"] = "blade",
	["tianmo-gong"] = "force",
	["tianmo-jian"] = "sword",
	["tianmo-shou"] = "hand",
	["tianmo-zhang"] = "strike",
	["tiangang-zhang"] = "strike",
	["tianlong-xiang"] = "dodge",
	["tianshan-zhang"] = "staff",
	["tianwang-zhua"] = "claw",
	["tianyu-qijian"] = "sword",
	["tiezhang-zhangfa"] = "strike",
	["tiyunzong"] = "dodge",
	["weituo-chu"] = "club",
	["wudang-mianzhang"] = "strike",
	["wudu-yanluobu"] = "dodge",
	["wuhu-duanmendao"] = "blade",
	["wuxiang-zhi"] = "finger",
	["wuyue-jianfa"] = "sword",
	["xiangfu-lun"] = "hammer",
	["xianglong-zhang"] = "strike",
	["xiangmo-chu"] = "hammer",
	["xiantian-gong"] = "force",
	["xiaohun-zhang"] = "strike",
	["xiaoyaoyou"] = "dodge",
	["xiaoyao-jian"] = "sword",
	["xingyi-zhang"] = "strike",
	["xiuluo-dao"] = "blade",
	["xixing-dafa"] = "force",
	["xuanfeng-tui"] = "leg",
	["xuangong-quan"] = "cuff",
	["xuanming-shenzhang"] = "strike",
	["xuantian-wuji"] = "force",
	["xuantian-zhi"] = "finger",
	["xuantie-jianfa"] = "sword",
	["xuanxu-daofa"] = "blade",
	["xuanyin-jian"] = "sword",
	["xuedao-jing"] = "blade",
	["xunlei-jian"] = "sword",
	["yangjia-qiang"] = "spear",
	["yanling-shenfa"] = "dodge",
	["yanxing-daofa"] = "blade",
	["yijin-jing"] = "force",
	--["yingou-bifa"] = "brush",
	["yinlong-bian"] = "whip",
	["yingshe-shengsibo"] = "claw",
	["yinsuo-jinling"] = "whip",
	["yitian-tulong"] = "sword",
	["yiyang-zhi"] = "finger",
	["yizhi-chan"] = "finger",
	["yinyun-ziqi"] = "force",
	["youlong-bian"] = "whip",
	["youlong-shenfa"] = "dodge",
	["youming-zhao"] = "claw",
	["yuenu-jian"] = "sword",
	["yueying-wubu"] = "dodge",
	["yunu-jianfa"] = "sword",
	["yunu-xinjing"] = "force",
	["yunu-shenfa"] = "dodge",
	["yuxiao-jian"] = "sword",
	["yuxue-dunxing"] = "dodge",
	["zhaixingshu"] = "dodge",
	["zhemei-shou"] = "hand",
	["zhenshan-mianzhang"] = "strike",
	["zhentian-quan"] = "cuff",
	["zhong-qiang"] = "spear",
	["zhongyuefeng"] = "dodge",
	["zhuihun-gou"] = "hook",
	["zhusha-zhang"] = "strike",
	["zixia-gong"] = "force",
	["zuibaxian"] = "dodge",
	["zui-gun"] = "club",
	["tianmo-gun"] = "club",
	["qixian-wuxingjian"] = "sword"
}

skillsEnable = {
	["anying-fuxiang"] = "dodge",
	["anran-zhang"] = "strike",
	["bahuang-gong"] = "force",
	["baihua-cuoquan"] = "cuff",
	["banruo-zhang"] = "strike",
	["beiming-shengong"] = "force",
	["bihai-chaosheng"] = "force",
	["canglang-goufa"] = "hook",
	["canhe-zhi"] = "finger",
	["caoshang-fei"] = "dodge",
	["chongling-jian"] = "sword",
	["chousui-zhang"] = "strike",
	["chuanyun-tui"] = "leg",
	["cihang-bian"] = "whip",
	["cibei-dao"] = "blade",
	["cuixin-zhang"] = "strike",
	["cuogu-shou"] = "hand",
	["dafumo-quan"] = "cuff",
	["dagou-bang"] = "stick",
	["damo-jian"] = "sword",
	["qianzhu-wandushou"] = "hand",
	["dashou-yin"] = "hand",
	["ding-dodge"] = "dodge",
	["duanjia-jianfa"] = "sword",
	["duanjia-quan"] = "cuff",
	["dugu-jiujian"] = "sword",
	["dulong-dafa"] = "force",
	["duoming-jinhua"] = "throwing",
	["fanliangyi-dao"] = "blade",
	["fengmo-zhang"] = "staff",
	["fengyun-shou"] = "hand",
	["fuhu-quan"] = "cuff",
	["fumo-jian"] = "sword",
	["fuqin-shi"] = "whip",
	["furong-jinzhen"] = "throwing",
	["guiyuan-tunafa"] = "force",
	["hamabu"] = "dodge",
	["hamagong"] = "force",
	["hanbing-mianzhang"] = "strike",
	["hanbing-shenzhang"] = "strike",
	["hanbing-zhenqi"] = "force",
	["haotian-zhang"] = "strike",
	["hansha-sheying"] = "throwing",
	["hengshan-jian"] = "sword",
	["hengshan-jianfa"] = "sword",
	["henshan-jianfa"] = "sword",
	["huagong-dafa"] = "force",
	["huagu-mianzhang"] = "strike",
	["huanmo-wubu"] = "dodge",
	["huanmo-longtianwu"] = "dodge",
	["huanyin-zhi"] = "finger",
	["huashan-jianfa"] = "sword",
	["huashan-qigong"] = "force",
	["huashan-shenfa"] = "dodge",
	["huifeng-bian"] = "whip",
	["huifeng-jian"] = "sword",
	["hujia-daofa"] = "blade",
	["huntian-qigong"] = "force",
	["hunyuan-zhang"] = "strike",
	["huoyan-dao"] = "strike",
	["huyan-qiang"] = "spear",
	["jieshou-jiushi"] = "hand",
	["jimie-zhua"] = "claw",
	["jindao-heijian"] = "sword",
	["jingang-quan"] = "cuff",
	["jinshe-jianfa"] = "sword",
	["jinshe-zhangfa"] = "strike",
	["jinshe-zhuifa"] = "throwing",
	["jinwu-daofa"] = "blade",
	["jinyan-gong"] = "dodge",
	["jiuyang-shengong"] = "force",
	["jiuyin-baiguzhua"] = "claw",
	["jiuyin-shenfa"] = "dodge",
	["jiuyin-shenzhang"] = "strike",
	["jiuyin-shenzhua"] = "claw",
	["jiuyin-zhengong"] = "force",
	["juehu-shou"] = "hand",
	["kaishan-fu"] = "axe",
	["kaishan-zhang"] = "strike",
	["kongming-quan"] = "cuff",
	["kuaihuo-zhang"] = "strike",
	["kuihua-feiying"] = "dodge",
	["kuihua-mogong"] = "force",
	["kuihua-shengong"] = "force",
	["kunlun-zhang"] = "strike",
	["kurong-changong"] = "force",
	["lanhua-shou"] = "hand",
	["lengquan-shengong"] = "force",
	["liangyi-jian"] = "sword",
	["lianhua-zhang"] = "strike",
	["lietian-fu"] = "axe",
	["liehuo-jian"] = "sword",
	["lieyan-dao"] = "blade",
	["lingbo-weibu"] = "dodge",
	["lingshe-bianfa"] = "whip",
	["lingshe-quanfa"] = "cuff",
	["lingxu-bu"] = "dodge",
	["linji-zhuang"] = "force",
	["liuhe-daofa"] = "blade",
	["liuyang-zhang"] = "strike",
	["liuye-daofa"] = "blade",
	["longxiang-boruo"] = "force",
	["longzhua-gong"] = "claw",
	["luohan-quan"] = "cuff",
	["luoying-zhang"] = "strike",
	["mantian-huayu"] = "throwing",
	["meinu-quanfa"] = "cuff",
	["miaojia-jianfa"] = "sword",
	["murong-daofa"] = "blade",
	["murong-jianfa"] = "sword",
	["nianhua-zhi"] = "finger",
	["ningxue-shenzhao"] = "claw",
	["ningxue-shenzhua"] = "claw",
	["pangen-fu"] = "axe",
	["pixie-jian"] = "sword",
	["piaomiao-shenfa"] = "dodge",
	["piaoyi-bu"] = "dodge",
	["piaoyi-shenfa"] = "dodge",
	["pinxu-lingfeng"] = "dodge",
	["pomopima-jian"] = "sword",
	["poyu-quan"] = "cuff",
	["qiantian-yiyang"] = "force",
	["qianye-shou"] = "hand",
	["qianzhu-wandushou"] = "hand",
	["qingyan-zhang"] = "strike",
	["qishang-quan"] = "cuff",
	["quanzhen-jianfa"] = "sword",
	["ranmu-daofa"] = "blade",
	["riyue-bian"] = "whip",
	["ruyi-dao"] = "blade",
	["ruying-suixingtui"] = "leg",
	["sanhua-zhang"] = "strike",
	["sanyin-zhua"] = "claw",
	["shaolin-shenfa"] = "dodge",
	["shaolin-tantui"] = "leg",
	["shenghuo-lingfa"] = "dagger",
	["shenghuo-shengong"] = "force",
	["shenlong-tuifa"] = "leg",
	["shenxing-baibian"] = "dodge",
	["shenyuan-gong"] = "force",
	["shenzhao-jing"] = "force",
	["shexing-diaoshou"] = "hand",
	["shuishangpiao"] = "dodge",
	["sixiang-zhang"] = "strike",
	["songshan-jian"] = "sword",
	["songshan-qigong"] = "force",
	["songyang-bian"] = "whip",
	["songyang-shou"] = "hand",
	["songyang-zhang"] = "strike",
	["suibo-zhuliu"] = "dodge",
	["suohou-shou"] = "hand",
	["taiji-jian"] = "sword",
	["taiji-quan"] = "cuff",
	["taiji-shengong"] = "force",
	["taishan-jianfa"] = "sword",
	["taixuan-gong"] = "strike",
	["taizu-quan"] = "cuff",
	["tangshi-jianfa"] = "sword",
	["tanzhi-shentong"] = "finger,throwing",
	["taxue-wuhen"] = "dodge",
	["tenglong-bifa"] = "dagger",
	["tianmo-dao"] = "blade",
	["tianmo-gong"] = "force",
	["tianmo-jian"] = "sword",
	["tianmo-shou"] = "hand",
	["tianmo-zhang"] = "strike",
	["tiangang-zhang"] = "strike",
	["tianlong-xiang"] = "dodge",
	["tianluo-diwang"] = "hand",
	["tianshan-zhang"] = "staff",
	["tianwang-zhua"] = "claw",
	["tianyu-qijian"] = "sword",
	["tiezhang-zhangfa"] = "strike",
	["tiyunzong"] = "dodge",
	["weituo-chu"] = "club",
	["wudang-mianzhang"] = "strike",
	["wudu-yanluobu"] = "dodge",
	["wuhu-duanmendao"] = "blade",
	["wuxiang-zhi"] = "finger",
	["wuyue-jianfa"] = "sword",
	["xiangfu-lun"] = "hammer",
	["xianglong-zhang"] = "strike",
	["xiangmo-chu"] = "hammer",
	["xiantian-gong"] = "force",
	["xiaohun-zhang"] = "strike",
	["xiaoyaoyou"] = "dodge",
	["xiaoyao-jian"] = "sword",
	["xingyi-zhang"] = "strike",
	["xiuluo-dao"] = "blade",
	["xixing-dafa"] = "force",
	["xuanfeng-tui"] = "leg",
	["xuangong-quan"] = "cuff",
	["xuanming-shenzhang"] = "strike",
	["xuantian-wuji"] = "force",
	["xuantian-zhi"] = "finger",
	["xuantie-jianfa"] = "sword",
	["xuanxu-daofa"] = "blade",
	["xuanyin-jian"] = "sword",
	["xuedao-jing"] = "blade",
	["xunlei-jian"] = "sword",
	["yangjia-qiang"] = "spear",
	["yanling-shenfa"] = "dodge",
	["yanxing-daofa"] = "blade",
	["yijin-jing"] = "force",
	--["yingou-bifa"] = "brush",
	["yinlong-bian"] = "whip",
	["yingshe-shengsibo"] = "claw,hand",
	["yinsuo-jinling"] = "whip",
	["yitian-tulong"] = "sword",
	["yiyang-zhi"] = "finger",
	["yizhi-chan"] = "finger",
	["yinyun-ziqi"] = "force",
	["youlong-bian"] = "whip",
	["youlong-shenfa"] = "dodge",
	["youming-zhao"] = "claw",
	["yuenu-jian"] = "sword",
	["yueying-wubu"] = "dodge",
	["yunu-jianfa"] = "sword",
	["yunu-xinjing"] = "force",
	["yunu-shenfa"] = "dodge",
	["yuxiao-jian"] = "sword",
	["yuxue-dunxing"] = "dodge",
	["zhaixingshu"] = "dodge",
	["zhemei-shou"] = "hand",
	["zhenshan-mianzhang"] = "strike",
	["zhentian-quan"] = "cuff",
	["zhong-qiang"] = "spear",
	["zhongyuefeng"] = "dodge",
	["zhuihun-gou"] = "hook",
	["zhusha-zhang"] = "strike",
	["zixia-gong"] = "force",
	["zuibaxian"] = "dodge",
	["zui-gun"] = "club",
	["qixian-wuxingjian"] = "sword",
	["tianmo-gun"] = "club"
}

skillHubei = {
	["longzhua-gong"] = "yizhi-chan",
	["yizhi-chan"] = "longzhua-gong",
	["jingang-quan"] = "banruo-zhang",
	["banruo-zhang"] = "jingan-quan",
	["ruiying-suixingtui"] = "qianye-shou",
	["qianye-shou"] = "ruying-suixingtui",
	["sanhua-zhang"] = "nianhua-zhi",
	["nianhua-zhi"] = "sanhua-zhang",
	["xuanfeng-tui"] = "luoying-zhang",
	["luoying-zhang"] = "xuanfeng-tui",
	["wuxiang-zhi"] = "luohan-quan",
	["luohan-quan"] = "wuxiang-zhi"
}

skillPfm = {}

masterRoom = {
	--少林派
	["无名老僧"] = "嵩山少林里屋",
	["渡难"] = "嵩山少林金刚伏魔圈",
	["渡劫"] = "嵩山少林金刚伏魔圈",
	["渡厄"] = "嵩山少林金刚伏魔圈",
	--桃花岛
	["陆乘风"] = "归云庄书房",
	["陆冠英"] = "归云庄前厅",
	["黄药师"] = "桃花岛积翠亭",
	--华山派
	["岳不群"] = "华山正气堂",
	["宁中则"] = "华山正气堂",
	["穆人清"] = "华山石屋",
	--["封不平"]   = "华山山涧",
	--["从不弃"]   = "华山山涧",
	--["成不忧"]   = "华山山涧",

	--武当派
	["谷虚道长"] = "武当山复真观",
	["俞岱岩"] = "武当山炼丹房",
	["莫声谷"] = "武当山天乙真庆宫",
	["宋远桥"] = "武当山三清殿",
	["张三丰"] = "武当山后山小院",
	["俞莲舟"] = "武当山小径"
}

function check_skills()
	local l_skills = " "
	if matches[4] then
		l_skills = l_skills .. matches[4]
	end
	if matches[5] then
		l_skills = l_skills .. matches[5]
	end
	if matches[6] then
		l_skills = l_skills .. matches[6]
	end
	l_skills = utf8.trim(l_skills)
	skills[l_skills] = skills[l_skills] or {}
	skills[l_skills].lvl = tonumber(matches[7])
	skills[l_skills].pot = tonumber(matches[8])
	skills[l_skills].name = utf8.trim(matches[3])
	if skills[l_skills].lvl >= 300 then
		skills[l_skills].mstlvl = 300
	end
	if l_skill == "force" and skills[l_skills].mstlvl < 220 and skills[l_skills].mstlvl == hp.pot_max - 101 then
		skills[l_skills].mstlvl = nil
	end
	-- GUI 刷新显示技能
	GUIShow_Skills()
end

function jifaAll()
    for p in pairs(skills) do
        local sk = qrySkillEnable(p)
        if sk and sk["force"] and perform.force and perform.force == p then
            exe("jifa force " .. p)
        end
        if sk and not sk["force"] then
            for q in pairs(sk) do
                if skills[q] and skills[p].lvl >= skills[q].lvl then
                    exe("jifa " .. q .. " " .. p)
                end
            end
        end
    end
end
